---
# roles/generate_appregdefs/tasks/render_single_appdef.yaml

- name: Ensure tmp_render_dir fact is set
  set_fact:
    tmp_render_dir: "{{ tmp_render_dir | default('/tmp') }}"

- name: Prepare appdefs dict for Jinja context
  set_fact:
    appdefs:
      overrides: "{{ appdefs_overrides }}"

- name: Extract template basename for Jinja context
  set_fact:
    template_name: "{{ item.path | basename | regex_replace('\\.j2$', '') }}"

- name: Render AppDef to temp file
  template:
    src:  "{{ item.path }}"
    dest: "{{ tmp_render_dir }}/{{ template_name }}.{{ render_timestamp }}.rendered.appdef.yml"
  vars:
    appdefs:     "{{ appdefs }}"
    current_env: "{{ current_env }}"

- name: Set rendered AppDef path
  set_fact:
    appdef_rendered_path: "{{ tmp_render_dir }}/{{ template_name }}.{{ render_timestamp }}.rendered.appdef.yml"

- name: Read rendered AppDef into raw string
  slurp:
    src: "{{ appdef_rendered_path }}"
  register: appdef_rendered_slurp

- name: Decode rendered AppDef
  set_fact:
    appdef_raw_rendered: "{{ appdef_rendered_slurp.content | b64decode }}"

- name: Parse rendered AppDef YAML into a dict
  set_fact:
    appdef_content: "{{ appdef_raw_rendered | from_yaml }}"

- name: Extract name (and other fields) for our final filename
  set_fact:
    appdef_name: "{{ appdef_content.name }}"
    artifactId: "{{ appdef_content.artifactId }}"
    groupId:    "{{ appdef_content.groupId }}"

- name: Save rendered AppDef to final path
  copy:
    content: "{{ appdef_raw_rendered }}"
    dest:    "{{ current_env_dir }}/AppDefs/{{ appdef_name }}.appdef.yml"
    mode:    '0644'
  when: appdef_name is defined and appdef_name | length > 0
