service-activator-integration-cred:
  type: usernamePassword
  data:
    username: 'test_username'
    password: 'test_password'
tibco-integration-cred:
  type: usernamePassword
  data:
    username: 'test_username'
    password: 'test_password'
