### default paths
artifact_dest: /tmp/artifact.zip
build_env_path: /build_env
envgen_debug: "{{ lookup('env', 'envgen_debug') }}"

env_name: "{{ lookup('env', 'ENV_NAME') }}"
cluster_name: "{{ lookup('env', 'CLUSTER_NAME') }}"
DEPLOYMENT_SESSION_ID: "{{ lookup('env', 'DEPLOYMENT_SESSION_ID') }}"
environment_name: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
base_dir: "{{ lookup('env', 'CI_PROJECT_DIR') }}"
env_template_vers: "{{ lookup('env', 'ENV_TEMPLATE_VERSION') }}"

### configuration files
envs_directory_path:   "{{ base_dir }}/environments"
registry_config_path: "{{ base_dir }}/configuration/registry.yml"
cred_config_path:     "{{ base_dir }}/configuration/credentials/credentials.yml"

instance_secret_key: "{{ lookup('env', 'SECRET_KEY') }}"
COMMIT_ENV: "{{ lookup('env', 'COMMIT_ENV)') }}"
