env_name: "{{ lookup('env', 'ENV_NAME') }}"
base_dir: "{{ lookup('env', 'CI_PROJECT_DIR') }}"
envgen_debug: "{{ lookup('env', 'envgen_debug') }}"

# path to discovery files
envs_directory_path: "{{ base_dir }}/environments"

dest_archive_path: "/tmp/archive.zip"
dest_unpack_files: "/tmp/passport"
passport_path: "{{ base_dir }}/configuration/group_vars/{{ env_name }}"

# gitlab ci/cd variable for encrypt/decrypt sensitive data
secret_key_var_name: "SECRET_KEY"
instance_secret_key: "{{ lookup('env', secret_key_var_name) }}"
discovery_job_name: "trigger_discovery_passport"
auto_discovery_job_name: "trigger-discovery-passport.{{ env_name | replace('_', '-') }}-trigger"
cred_config_path:     "{{ base_dir }}/configuration/credentials/credentials.yml"
integration_config_path: "{{ base_dir }}/configuration/integration.yml"

# if try to get passport from this repo
get_passport_job_name: "get_cloud_passport"
url_pipe_bridges: "{{ lookup('env','CI_API_V4_URL') }}/projects/{{ lookup('env','CI_PROJECT_ID') }}/pipelines/{{ lookup('env','CI_PIPELINE_ID') }}/bridges"
url_pipe_jobs: "{{ lookup('env','CI_API_V4_URL') }}/projects/{{ downstream_project_id }}/pipelines/{{ downstream_pipe_id }}/jobs"

# if try to get passport from discorvery-tool repo
archive_url: "{{ lookup('env','CI_API_V4_URL') }}/projects/{{ lookup('env','parent_project_id') }}/jobs/artifacts/{{ lookup('env','parent_pipe_branch') }}/download?job={{ lookup('env','parent_job_name') }}"
gitlab_vars_api: "{{ lookup('env','CI_API_V4_URL') }}/projects/{{ lookup('env','parent_project_id') }}/variables"

header_text: "The contents of this file is generated from Cloud Passport discovery procedure.\nContents will be overwritten by next discovery.\nPlease do not modify this file."
