---
### script arguments
- name: Set script arguments
  set_fact:
    script_args: "--env_definition_path={{ env_definition_path }} --version_to_add={{ env_template_vers }}"

- name: 03.1 Commit and push changes to git
  shell: |
    cd ${CI_PROJECT_DIR}
    . /module/scripts/git_commit.sh
