---

- name: Check if sd.yaml exists in {{ sd_output_dir }}/{{ sd_cluster_name }}/{{ sd_env }}/Inventory/solution-descriptor
  stat:
    path: "{{ sd_output_dir }}/{{ sd_cluster_name }}/{{ sd_env }}/Inventory/solution-descriptor/sd.yaml"
  register: sd_file_existence

- name: Load applications data from sd.yaml
  include_vars:
    file: "{{ sd_output_dir }}/{{ sd_cluster_name }}/{{ sd_env }}/Inventory/solution-descriptor/sd.yaml"
    name: sd_config
  when: sd_file_existence.stat.exists

- name: Check that 'applications'-key exists
  assert:
    that:
      - "'applications' in sd_config"
      - "sd_config.applications is sequence"
    success_msg: "Root 'applications' key exists and is a list"
    fail_msg: "Missing or invalid 'applications' key in root"
  when: sd_file_existence.stat.exists

- name: Validate each application entry
  assert:
    that:
      - "'version' in item"
      - "'deployPostfix' in item"
      - "item.version is string"
      - "item.deployPostfix is string"
    success_msg: "Valid application entry: {{ item }}"
    fail_msg: "Invalid application entry: {{ item | to_nice_json }}"
  loop: "{{ sd_config.applications }}"
  loop_control:
    label: "Application {{ item.version | default('unknown') }}"
  when: sd_file_existence.stat.exists

- name: All checks passed
  debug:
    msg: "All required fields are present and valid!"
  when: sd_file_existence.stat.exists

- name: Initialize result structure
  set_fact:
    all_environments: {}
  when: sd_file_existence.stat.exists

- name: Process each application
  block:
    - name: Extract application components
      set_fact:
        app_name: "{{ item.version.split(':')[0] | trim }}"
        app_version: "{{ item.version.split(':')[1] | trim if (item.version | count(':') > 0) else '' }}"
        deploy_postfix: "{{ item.deployPostfix }}"

    - name: Build template path
      set_fact:
        template_path: >-
          {{ 
            (current_env_template.namespaces | default('templates')) | regex_replace('/$', '') 
            ~ '/' 
            ~ deploy_postfix 
            ~ '.yaml.j2' 
          }}

    - name: Debug template path
      debug:
        msg: "Looking for template at: {{ template_path }}"

    - name: Check template existence
      stat:
        path: "{{ template_path }}"
      register: template_check

    - name: Extract namespace from template
      set_fact:
        namespace: >-
          {% if template_check.stat.exists %}
            {% set content = lookup('file', template_path).split('\n') %}
            {% set ns_line = content | select('match', '^\\s*name:') | list | first %}
            {{ 
              (ns_line.split(':', 1)[1] | trim | regex_replace('[\'"]', '')) 
              | default('NULL') 
            }}
          {% else %}
            NULL
          {% endif %}

    - name: Update environment structure
      set_fact:
        all_environments: >-
          {{
            all_environments | combine({
              app_name: {
                'deployPostfix': deploy_postfix,
                'namespace': namespace | default('NULL'),
                'version': app_version
              }
            }, recursive=true)
          }}
  loop: "{{ sd_config.applications }}"
  loop_control:
    label: "Processing {{ item.version }}"
  when: sd_file_existence.stat.exists


- name: Merge apps with env prefixes
  set_fact:
    merged_apps: >-
      {%- set result = {} -%}
      {%- for env_path, env_data in all_environments.items() -%}
        {%- set env_name = env_path | basename | splitext | first -%}
        {%- for app_name, app_data in env_data.items() -%}
          {%- set unique_key = app_name -%}
          {%- set _ = result.update({unique_key: app_data}) -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ result }}
  when: sd_file_existence.stat.exists

- name: Show all transformed data
  debug:
    var: merged_apps
  when: sd_file_existence.stat.exists

- set_fact:
    current_env: "{{ current_env | combine({'solution_structure': merged_apps}) }}"
  when: sd_file_existence.stat.exists

- name: Show current_env.solution_structure
  debug:
    var: current_env.solution_structure
  when: sd_file_existence.stat.exists