---

- name: Extract application components
  set_fact:
    app_name: "{{ item.version.split(':')[0] | trim }}"
    app_version: "{{ item.version.split(':', 1)[1] | trim if (item.version | count(':') > 0) else '' }}"
    deploy_postfix: "{{ item.deployPostfix.split('.')[0] | trim }}"

- name: Build template path
  set_fact:
    template_path: "{{ (current_env_template.namespaces) | trim('/') }}/{{ deploy_postfix }}.yml.j2"

- name: Validate template file
  stat:
    path: "{{ template_path }}"
  register: template_stat

- name: Extract namespace
  set_fact:
    namespace: >-
      {% if template_stat.stat.exists %}
        {% set ns_line = lookup('file', template_path).split('\n') | select('match', '^name:') | list | first %}
        {{ (ns_line.split(':', 1)[1] | trim | regex_replace('[\'"]', '') | default('NULL') }}
      {% else %}
        NULL
      {% endif %}

- name: Update environment structure
  set_fact:
    all_environments: >-
      {% set ns = namespace(result=all_environments | default({})) %}
      {% set _ = ns.result.update({
          app_name: {
            'deployPostfix': deploy_postfix,
            'namespace': namespace,
            'version': app_version
          }
        }) %}
      {{ ns.result }}
