name: "Build All Docker Images"

run-name: "Build all docker images for commit ${{ github.sha }}"

on:
  workflow_dispatch:
  push:
    branches:
      - '**'  

env:
  REGISTRY: ghcr.io

jobs:
  tests:
    uses: ./.github/workflows/perform_tests.yml

  build-qubership-gcip:
    needs: [tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Build Qubership GCIP Docker Image
        uses: ./.github/actions/build-qubership-gcip
        with:
          registry: ${{ env.REGISTRY }}
          git-user: ${{ secrets.GIT_USER }}
          git-token: ${{ secrets.GIT_TOKEN }}

  build-qubership-envgene:
    needs: [tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Build Qubership Envgene Docker Image
        uses: ./.github/actions/build-qubership-envgene
        with:
          registry: ${{ env.REGISTRY }}
          gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}

  build-instance-repo-pipeline:
    needs: [tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Build Instance Repo Pipeline Docker Image
        uses: ./.github/actions/build-instance-repo-pipeline
        with:
          registry: ${{ env.REGISTRY }}
          gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}

  build-effective-set-generator:
    needs: [tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Build Effective Set Generator Docker Image
        uses: ./.github/actions/build-effective-set-generator
        with:
          registry: ${{ env.REGISTRY }}
          git-user: ${{ secrets.GIT_USER }}
          git-token: ${{ secrets.GIT_TOKEN }} 