# Cluster-specific configuration overrides for cluster-01
default_values:
  # Default values for AppDef templates specific to this cluster
  appdef:
    deployParameters:
      param1: "cluster01_override_value1"
      cluster_specific_param: "cluster01_specific_value"
    technicalConfigurationParameters:
      tech_param1: "cluster01_override_tech_value1"
  
  # Default values for RegDef templates specific to this cluster
  regdef:
    mavenConfig:
      repositoryDomainName: "maven.cluster01.example.com"
    dockerConfig:
      snapshotUri: "docker.cluster01.example.com/snapshot"
      stagingUri: "docker.cluster01.example.com/staging"

# Override patterns specific to this cluster
override_patterns:
  # Pattern for environment-specific overrides within this cluster
  environment:
    pattern: "{{ env_name }}"
    values:
      env-01:
        appdef:
          deployParameters:
            param1: "cluster01_env01_value1"
        regdef:
          mavenConfig:
            targetSnapshot: "env01-snapshots"
      env-02:
        appdef:
          deployParameters:
            param1: "cluster01_env02_value1"
        regdef:
          mavenConfig:
            targetSnapshot: "env02-snapshots"
